using ExcentOne.Application.Features.Commands;
using System;

namespace Accounting.Application.Features
{
    public class CreateInventoryAdjustment : ICreateEntity<Guid, Guid>
    {
        public Guid Id => Guid.NewGuid();

        public Guid? Customer { get; set; }

        public DateTime? TranDate { get; set; }

        public Guid? Location { get; set; }

        public bool? IsInactive { get; set; }

        // Optional - will be auto-generated by backend if not provided
        public string? SequenceNumber { get; set; }

        public Guid Form { get; set; }

        public string? CreatedBy { get; set; }
    }
}
