// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Accounting.Persistence.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Accounting.Persistence
{
    public partial class AccountingDbContext
    {
        private IAccountingDbContextProcedures _procedures;

        public virtual IAccountingDbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new AccountingDbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IAccountingDbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class AccountingDbContextProcedures : IAccountingDbContextProcedures
    {
        private readonly AccountingDbContext _context;

        public AccountingDbContextProcedures(AccountingDbContext context)
        {
            _context = context;
        }

        public virtual async Task<int> CheckBlockingReferencesAsync(string tableName, string primaryKeyColumn, string primaryKeyValue, string excludeTables, OutputParameter<int?> totalCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterTotalCount = new SqlParameter
            {
                ParameterName = "TotalCount",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = totalCount?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "TableName",
                    Size = 256,
                    Value = tableName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PrimaryKeyColumn",
                    Size = 256,
                    Value = primaryKeyColumn ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PrimaryKeyValue",
                    Size = -1,
                    Value = primaryKeyValue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ExcludeTables",
                    Size = -1,
                    Value = excludeTables ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterTotalCount,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[CheckBlockingReferences] @TableName = @TableName, @PrimaryKeyColumn = @PrimaryKeyColumn, @PrimaryKeyValue = @PrimaryKeyValue, @ExcludeTables = @ExcludeTables, @TotalCount = @TotalCount OUTPUT", sqlParameters, cancellationToken);

            totalCount?.SetValue(parameterTotalCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> GetReferenceCountAsync(string tableName, string primaryKeyColumn, string primaryKeyValue, OutputParameter<int?> totalCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterTotalCount = new SqlParameter
            {
                ParameterName = "TotalCount",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = totalCount?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "TableName",
                    Size = 256,
                    Value = tableName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PrimaryKeyColumn",
                    Size = 256,
                    Value = primaryKeyColumn ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PrimaryKeyValue",
                    Size = -1,
                    Value = primaryKeyValue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterTotalCount,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[GetReferenceCount] @TableName = @TableName, @PrimaryKeyColumn = @PrimaryKeyColumn, @PrimaryKeyValue = @PrimaryKeyValue, @TotalCount = @TotalCount OUTPUT", sqlParameters, cancellationToken);

            totalCount?.SetValue(parameterTotalCount.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
