// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Accounting.Persistence.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Accounting.Persistence
{
    public partial interface IAccountingDbContextProcedures
    {
        Task<int> CheckBlockingReferencesAsync(string tableName, string primaryKeyColumn, string primaryKeyValue, string excludeTables, OutputParameter<int?> totalCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GetReferenceCountAsync(string tableName, string primaryKeyColumn, string primaryKeyValue, OutputParameter<int?> totalCount, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
