using ExcentOne.Application.Features.Commands;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Accounting.Application.Features
{
    public class CreateCustomerPayment : ICreateEntity<Guid, Guid>
    {
        public Guid Id => Guid.NewGuid();

        public Guid? Location { get; set; }

        public Guid Customer { get; set; }

        public Guid Form { get; set; }

        public decimal? Amount { get; set; }

        public decimal? AppliedAmount { get; set; }

        public decimal? UnAppliedAmount { get; set; }

        public string? SequenceNumber { get; set; } // Optional - will be auto-generated by backend if not provided

        public DateTime? PaymentDate { get; set; }

        public Guid? Status { get; set; }
    }
}
