using ExcentOne.Application.Features.Commands;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Accounting.Application.Features
{
    public class CreateDebitMemo : ICreateEntity<Guid, Guid>
    {
        public Guid Id => Guid.NewGuid();

        public Guid CustomerID { get; set; }

        public Guid LocationID { get; set; }

        public DateTime TranDate { get; set; }

        public decimal TotalAmount { get; set; }

        public Guid Form { get; set; }

        public string? SequenceNumber { get; set; } // Optional - will be auto-generated by backend if not provided

        public decimal? AmountDue { get; set; }

        public decimal? AmountPaid { get; set; }

        public decimal? GrossAmount { get; set; }

        public decimal? TaxTotal { get; set; }

        public decimal? SubTotal { get; set; }

        public decimal? NetTotal { get; set; }

        public Guid? Status { get; set; }

        public string? CreatedBy { get; set; }
    }
}
